stages:
    - deploy

deploy:
    stage: deploy
    script:
        - 'curl --header "Job-Token: $CI_JOB_TOKEN" --data branch=<branch> "https://gitlab.com/api/v4/projects/$CI_PROJECT_ID/packages/composer"'
